import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import { useEffect, useState } from "react";
import About from "../components/About";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";
import Experience from "../components/Experience";
import Education from "../components/Education";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [show, setShow] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setShow(false);
    }, 2500);
    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/T-removebg-preview.png"
          sizes="2002x2002 1000x1000"
        />
      </Head>
      <main className="bg-black">
        {show && (
          <div
            style={{
              height: "100vh",
              backgroundColor: "black",
              textAlign: "center",
              alignItems: "center",
              justifyContent: "center",
              display: "flex",
            }}
          >
            <img
              src="https://s3.brilliant.com.bd/tahsin/kheyaPortfolio/K.gif"
              style={{
                display: show ? "block" : "none",
                height: "20vh",
              }}
              alt="alternatetext"
            />{" "}
          </div>
        )}
        {!show && (
          <div>
            {" "}
            <Navbar />
            <About />
            <Education />
            <Experience />
            {/* <Footer /> */}
            {window.innerWidth < 1060 ? <Footer /> : <Sidebar />}
          </div>
        )}
      </main>
    </>
  );
}
